# Generated by Django 3.2 on 2023-10-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='instructions',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
